specVersion: 1.0.0
name: xion-indexer
version: 1.0.0
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This is the indexer solution for the xion chain
repository: "https://github.com/subquery/cosmos-subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: xion-local-testnet-1
  # This endpoint must be a public non-pruned archive node
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime.
  # This is a public node that is rate limited, which will affect indexing speed.
  # When developing your project we strongly suggest getting a private API key.
  endpoint: "rpc://192.168.1.25:26657"
  # testnet -> https://rpc.xion-testnet-1.burnt.com:443
  port: 26657
dataSources:
  - kind: cosmos/Runtime
    startBlock: 121643
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleHubContractInstantiate
          kind: cosmos/EventHandler
          filter:
            type: instantiate
            attribute:
              code_id: "10"
            messageFilter:
              type: /cosmwasm.wasm.v1.MsgInstantiateContract
              
        - handler: handleHubContractInstantiateMetadata
          kind: cosmos/EventHandler
          filter:
            type: wasm
            messageFilter:
              type: /cosmwasm.wasm.v1.MsgInstantiateContract
