// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.174.0
//   protoc               v4.24.4
// source: cosmos/msg/v1/msg.proto

/* eslint-disable */

export const protobufPackage = "cosmos.msg.v1";
